---
- name: Get fish shell binary location
  command: which fish
  register: fish
  changed_when: false

- name: Set fish as default shell
  user: name="{{ lookup('env', 'USER') }}" shell="{{ fish.stdout }}"
