---
- name: Install apt packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ install_packages.from_apt }}"

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items: "{{ install_packages.from_pip }}"

- name: Add GPG Keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ install_packages.from_repo.gpg_keys }}"

- name: Add apt repositories
  apt_repository:
    repo: "deb {{ item }}"
    state: present
  with_items: "{{ install_packages.from_repo.repo_urls }}"

- name: Install packages from apt repositiries
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ install_packages.from_repo.package_names }}"

- name: Download from source to build
  ansible.builtin.git:
    repo: "{{ item.value.url }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ create_dev_dirs.5 }}/{{ item.value.url | basename }}"
    force: true
  with_dict: "{{ install_packages.from_source }}"

- name: Install packages from source
  command: "{{ item.1 }}"
  args:
    chdir: "{{ lookup('env', 'HOME') }}/{{ create_dev_dirs.5 }}/{{ item.0.url | basename }}/{{ item.0.chdir }}"
  with_subelements:
    - "{{ install_packages.from_source }}"
    - commands
  changed_when: false
