---
- name: Install apt packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ install_packages.from_apt }}"

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items: "{{ install_packages.from_pip }}"

- name: Add GPG Keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ install_packages.from_repo.gpg_keys }}"

- name: Add apt repositories
  apt_repository:
    repo: "deb {{ item }}"
    state: present
  with_items: "{{ install_packages.from_repo.repo_urls }}"

- name: Install packages from apt repositiries
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ install_packages.from_repo.package_names }}"

- name: Install packages from shell
  ansible.builtin.shell:
    cmd: "{{ item }}"
  with_items: "{{ install_packages.from_command }}"
  failed_when: false
  changed_when: false

- name: Download from source to build
  ansible.builtin.git:
    repo: "{{ item.value.url }}"
    dest: "{{ ansible_facts.env.HOME }}/{{ create_dev_dirs.2 }}/{{ item.key }}"
    force: true
  with_dict: "{{ install_packages.from_source }}"

- name: Install packages from source
  command: "{{ item.value.commands }}"
  args:
    chdir: "{{ ansible_facts.env.HOME }}/{{ create_dev_dirs.2 }}/{{ item.key }}{{ item.value.chdir }}"
  with_dict: "{{ install_packages.from_source }}"
  failed_when: false
  changed_when: false
