---
- name: Create dev directory structure
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: directory
    mode: u=rwx,g=rwx,o=rwx
  with_items: "{{ create_dev_dirs }}"
